version: "3.8"
services:
    test:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        TARGET_URL: "https://test.npgw.xyz/"
        CHROME_OPTIONS: "--headless --disable-dev-shm-usage --no-sandbox --disable-gpu --window-size=1920,1080"